"""Industrial TileMEM SDK facade.

Use this package as:

    import tilemem as TM

The facade keeps customer-facing APIs stable while TilePO, TMAP, and backend
integration internals continue to evolve.
"""

from .sdk import (
    Backend,
    BackendCapability,
    BackendRegistry,
    CheckpointArtifact,
    DeploymentMode,
    HardwareProfile,
    MIR_SCHEMA_VERSION,
    MODEL_SPEC_SCHEMA_VERSION,
    MoETopology,
    ModelAdapter,
    ModelIR,
    ModelSpec,
    PUBLIC_MIR_INTERFACE,
    PrecisionIR,
    PredictionResult,
    ResidencyIR,
    RouteIR,
    RuntimeMode,
    ScaleLayout,
    ScheduleIR,
    ServingCommand,
    ServingResult,
    TMAPDecision,
    TileDType,
    TileFormat,
    TileHandle,
    TileIR,
    TileId,
    TileMEMPlan,
    WeightMatchResult,
    backend_registry,
    benchmark_dispatch_plan,
    build_manifest,
    build_mir,
    build_runtime_weight_aliases,
    build_serving_command,
    build_tile_checkpoint_map,
    build_tile_handles,
    checkpoint_weight_names,
    export_checkpoint_artifact,
    hardware_profile,
    infer_moe_topology,
    load_checkpoint_weight_map,
    load_hf_config,
    load_mir,
    match_checkpoint_weights,
    model_from_dict,
    model_spec,
    model_spec_from_dict,
    model_spec_from_hf_config,
    model_spec_to_dict,
    plan,
    plan_from_hf_config,
    predict_policy,
    register_backend,
    run_serving_backend,
    save_mir,
    summarize_v0_1_evidence,
    v0_1_headline_gain,
    validate_mir_dict,
)

__version__ = "0.12.0"

__all__ = [
    "Backend",
    "BackendCapability",
    "BackendRegistry",
    "CheckpointArtifact",
    "DeploymentMode",
    "HardwareProfile",
    "MIR_SCHEMA_VERSION",
    "MODEL_SPEC_SCHEMA_VERSION",
    "MoETopology",
    "ModelAdapter",
    "ModelIR",
    "ModelSpec",
    "PUBLIC_MIR_INTERFACE",
    "PrecisionIR",
    "PredictionResult",
    "ResidencyIR",
    "RouteIR",
    "RuntimeMode",
    "ScaleLayout",
    "ScheduleIR",
    "ServingCommand",
    "ServingResult",
    "TMAPDecision",
    "TileDType",
    "TileFormat",
    "TileHandle",
    "TileIR",
    "TileId",
    "TileMEMPlan",
    "WeightMatchResult",
    "__version__",
    "backend_registry",
    "benchmark_dispatch_plan",
    "build_manifest",
    "build_mir",
    "build_runtime_weight_aliases",
    "build_serving_command",
    "build_tile_checkpoint_map",
    "build_tile_handles",
    "checkpoint_weight_names",
    "export_checkpoint_artifact",
    "hardware_profile",
    "infer_moe_topology",
    "load_checkpoint_weight_map",
    "load_hf_config",
    "load_mir",
    "match_checkpoint_weights",
    "model_from_dict",
    "model_spec",
    "model_spec_from_dict",
    "model_spec_from_hf_config",
    "model_spec_to_dict",
    "plan",
    "plan_from_hf_config",
    "predict_policy",
    "register_backend",
    "run_serving_backend",
    "save_mir",
    "summarize_v0_1_evidence",
    "v0_1_headline_gain",
    "validate_mir_dict",
]
