"""Industrial TileMEM SDK facade.

Use this package as:

    import tilemem as TM

The facade keeps customer-facing APIs stable while TilePO, TMAP, and backend
integration internals continue to evolve.
"""

from .sdk import (
    Backend,
    BackendCapability,
    BackendRegistry,
    DeploymentMode,
    HardwareProfile,
    MIR_SCHEMA_VERSION,
    MODEL_SPEC_SCHEMA_VERSION,
    ModelAdapter,
    ModelIR,
    ModelSpec,
    PUBLIC_MIR_INTERFACE,
    PrecisionIR,
    PredictionResult,
    ResidencyIR,
    RouteIR,
    RuntimeMode,
    ScaleLayout,
    ScheduleIR,
    TMAPDecision,
    TileDType,
    TileFormat,
    TileHandle,
    TileIR,
    TileId,
    TileMEMPlan,
    backend_registry,
    benchmark_dispatch_plan,
    build_manifest,
    build_mir,
    build_tile_handles,
    hardware_profile,
    load_mir,
    model_from_dict,
    model_spec,
    model_spec_from_dict,
    model_spec_to_dict,
    plan,
    predict_policy,
    register_backend,
    save_mir,
    summarize_v0_1_evidence,
    v0_1_headline_gain,
    validate_mir_dict,
)

__version__ = "0.12.0"

__all__ = [
    "Backend",
    "BackendCapability",
    "BackendRegistry",
    "DeploymentMode",
    "HardwareProfile",
    "MIR_SCHEMA_VERSION",
    "MODEL_SPEC_SCHEMA_VERSION",
    "ModelAdapter",
    "ModelIR",
    "ModelSpec",
    "PUBLIC_MIR_INTERFACE",
    "PrecisionIR",
    "PredictionResult",
    "ResidencyIR",
    "RouteIR",
    "RuntimeMode",
    "ScaleLayout",
    "ScheduleIR",
    "TMAPDecision",
    "TileDType",
    "TileFormat",
    "TileHandle",
    "TileIR",
    "TileId",
    "TileMEMPlan",
    "__version__",
    "backend_registry",
    "benchmark_dispatch_plan",
    "build_manifest",
    "build_mir",
    "build_tile_handles",
    "hardware_profile",
    "load_mir",
    "model_from_dict",
    "model_spec",
    "model_spec_from_dict",
    "model_spec_to_dict",
    "plan",
    "predict_policy",
    "register_backend",
    "save_mir",
    "summarize_v0_1_evidence",
    "v0_1_headline_gain",
    "validate_mir_dict",
]
